# Site settings
title: Journey in the IT jungle
header-img: img/home-bg.png
email: petya.djanovska@gmail.com
copyright_name: PetyaDjanovska
description: > # this means to ignore newlines until "baseurl:"
  The ups and downs in learning how to code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  PetyaDjanovska
learn_profile: PetyaDjanovska
email_username: petya.djanovska@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
